apiVersion: v1
kind: Service
metadata:
  name: order-consumer-service
  labels:
    app: consumer-order
    tier: backend
    environment: production
  annotations:
    description: "Service para expor o microsserviço consumer-order"
spec:
  type: LoadBalancer
  selector:
    app: consumer-order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
