apiVersion: v1
kind: PersistentVolume
metadata:
  name: consumer-order-persistent-volume
  labels:
    app: consumer-order
    tier: backend
  annotations:
    description: "Volume persistente para dados do microsserviço consumer-order"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /data/consumer-order/logs
