name: .NET CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main

permissions:
  id-token: write  # Permissões para gerar o id-token

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore OrderConsumerService.sln

      - name: Build
        run: dotnet build OrderConsumerService.sln --configuration Release

      # - name: Run Unit Tests        
      #   run: dotnet test OrderConsumerService.Tests/OrderConsumerService.Tests.csproj --configuration Release --logger "console;verbosity=detailed"

      - name: Publish
        run: dotnet publish OrderConsumerService.Worker/OrderConsumerService.Worker.csproj --configuration Release --output OrderConsumerService.Worker/publish

      # --- Adicionando as etapas de Docker, ACR e AKS ---
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEFAULT_DIRECTORY_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure CLI (Using Managed Identity)
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Verificar se o cluster Kubernetes está acessível
        run: |
          if kubectl cluster-info; then
            echo "Cluster Kubernetes está acessível"
          else
            echo "Falha ao acessar o cluster Kubernetes"
            exit 1
          fi

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/k8s:latest -f OrderConsumerService.Worker/Dockerfile .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/k8s:latest

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.AKS_RESOURCE_GROUP }}'
          cluster-name: '${{ secrets.AKS_CLUSTER_NAME }}'

      - name: Update Kubernetes Resources
        run: |
          # Aplica ConfigMap (cria ou atualiza se necessário)
          kubectl apply -f OrderConsumerService.Worker/k8s/k8s-configmap.yml

          # Aplica Deployment (cria ou atualiza se necessário)
          kubectl apply -f OrderConsumerService.Worker/k8s/k8s-deployment.yml

          # Aplica PVC e PV (apenas cria ou atualiza, sem deletar)
          kubectl apply -f OrderConsumerService.Worker/k8s/k8s-persistent-volume.yml
          kubectl apply -f OrderConsumerService.Worker/k8s/k8s-persistent-volume-claim.yml

          # Aplica Service (cria ou atualiza se necessário)
          kubectl apply -f OrderConsumerService.Worker/k8s/k8s-service.yml

          # Espera o rollout do Deployment para garantir que a atualização foi bem-sucedida
          kubectl rollout status deployment/consumer-order-deployment
      
      - name: Update AKS Deployment with new image
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            OrderConsumerService.Worker/k8s/k8s-deployment.yml
            OrderConsumerService.Worker/k8s/k8s-service.yml
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/k8s:latest
          imagepullsecrets: |
            acr-auth

      - name: Cleanup
        if: always()
        run: |
          docker rm -f rabbitmq || true
          docker volume prune -f
